name: Compilador en la Nube
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código del repo
        uses: actions/checkout@v4

      - name: Configurar Rust y el Target para Celular
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android # <--- ESTO LE DA EL MOLDE DE PROCESADOR DE CELULAR

      - name: Forzar instalacion de Android Platform 30
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "platforms;android-30"

      - name: Instalar el empaquetador cargo-apk en la nube
        run: cargo install cargo-apk

      - name: ¡Compilar el APK al fierro!
        run: cargo apk build 

      - name: Guardar el APK terminado para descargarlo
        uses: actions/upload-artifact@v4
        with:
          name: MiAppNativaSkia
          path: target/release/apk/*.apk

